import { GoogleGenAI } from "@google/genai";
import { Product, GenerationConfig, MockupResult, MediumType } from "../types";

export async function generateMockup(
  products: Product[],
  medium: MediumType,
  config: GenerationConfig
): Promise<MockupResult> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

  const productParts = products.map(p => ({
    inlineData: {
      data: p.base64,
      mimeType: p.mimeType
    }
  }));

  const bgPart = config.background.type === 'custom' && config.background.customBase64 ? [{
    inlineData: {
      data: config.background.customBase64,
      mimeType: config.background.customMimeType || 'image/png'
    }
  }] : [];

  const styleDesc = config.style !== 'none' ? ` in a ${config.style} artistic style` : '';
  const textureDesc = config.texture !== 'none' ? ` with a ${config.texture} texture applied to the surfaces` : '';
  const bgDesc = config.background.type === 'custom' ? 'using the provided custom background' : `in a ${config.background.type} setting`;
  
  const prompt = `Create a realistic, high-quality marketing mockup of the provided product(s) ${products.map(p => p.name).join(', ')} on a ${medium}. 
  The scene should be ${bgDesc}${styleDesc}${textureDesc}. 
  Ensure the product(s) look natural, with correct lighting, shadows, and perspective on the ${medium}. 
  The products should be clearly visible and maintain their original design and features.
  If multiple products are provided, arrange them aesthetically on the ${medium}.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        ...productParts,
        ...bgPart,
        { text: prompt }
      ]
    }
  });

  const imagePart = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
  
  if (!imagePart || !imagePart.inlineData) {
    throw new Error("No image was generated by the AI.");
  }

  return {
    id: Math.random().toString(36).substr(2, 9),
    medium,
    imageUrl: `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`,
    prompt
  };
}

export async function optimizeImage(
  base64: string,
  mimeType: string,
  task: 'remove-bg' | 'enhance'
): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY! });

  const prompt = task === 'remove-bg' 
    ? "Remove the background from this image. Output only the product on a clean, pure white background. Maintain all product details and colors perfectly."
    : "Enhance this product image. Improve the lighting, sharpness, and overall quality while maintaining the original design and features. Output the enhanced product on a clean white background.";

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64,
            mimeType: mimeType
          }
        },
        { text: prompt }
      ]
    }
  });

  const imagePart = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
  
  if (!imagePart || !imagePart.inlineData) {
    throw new Error("Failed to optimize image.");
  }

  return `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`;
}
